### ISSUE TITLE
Slow pagination

### ISSUE THREAD

**Issue by vdbergh** [glinscott/fishtest#1220]
Looking at old tests is excruciatingly slow. The reason is that Fishtest uses the `.skip()` method of a cursor. However the `mongodb` documentation states that this will be slow if the number of documents to be skipped is large.

> The skip() method requires the server to scan from the beginning of the input results set before beginning to return results. 
> As the offset increases, skip() will become slower.

See https://docs.mongodb.com/manual/reference/method/cursor.skip/#definition.

One solution would be to equip runs with an indexed `count` field. This field could then be used for fast pagination.

`rundb::new_run()` should have a small critical section to atomically create a new counter value.

**Comment by ppigazzini** [comment]
Little reminder, better to check also the mongodb manual for version 4.2 to avoid issues:
https://docs.mongodb.com/v4.2/reference/method/cursor.skip/

After converting "runs" on PROD I will test on DEV the in-place upgrade to mongodb 4.4:
https://docs.mongodb.com/manual/release-notes/4.4-upgrade-standalone/

"pgns" collection on PROD is over 60GB, no way to use to usual process mongodump -> mongodb upgrade -> mongorestore

Yesterday I raised on PROD the feature compatibility to 4.2, it was still running with the 4.0: 
https://docs.mongodb.com/manual/release-notes/4.4-upgrade-standalone/#feature-compatibility-version

**Comment by vdbergh** [comment]
To implement the above solution it seemed most natural to use a transaction to a create a new run (I see no other way to do it robustly and fast). However to my surprise I got the following message. 
```
Transaction numbers are only allowed on a replica set member or mongos, full error: {'ok': 0.0, 'errmsg': 'Transaction numbers are only allowed on a replica set member or mongos', 'code': 20, 'codeName': 'IllegalOperation'}
```
So I followed the instructions here to convert my local mongodb instance to a replica set:

https://docs.mongodb.com/v4.0/tutorial/convert-standalone-to-replica-set/
https://docs.mongodb.com/manual/reference/configuration-options/#replication-options

It seems to be working. My mongod.conf now looks as follows
```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  mmapv1:
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1.75


# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  logRotate: reopen
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

#security:

#operationProfiling:

replication:
   replSetName: sr0

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:
```
```
